server:
  port: 8124


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.208.12.149:3306/cosmos
    username: cosmos
    password: BpS94rspcSDKbRAm

  redis:
    database: 1
    host: 8.208.12.149
    port: 6379
    timeout: 5000
    password: Tang168168
mybatis-plus:
  configuration:
    log-impl: ''
knife4j:
  basic:
    enable: true
    username: Noven
    password: Tang168168
